# Generated by Django 3.1.7 on 2021-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
