# Generated by Django 3.1.7 on 2021-03-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pelicula_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='slug',
        ),
    ]
