# Generated by Django 3.1.7 on 2021-03-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_pelicula_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion',
            field=models.PositiveSmallIntegerField(default='0', max_length=1),
        ),
    ]
